# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          extensions: mysqli, xmlwriter
          coverage: none
        env:
          fail-fast: true

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          mysql --version

      - run: npm install

      - run: composer install

      - run: composer run test
        env:
          MYSQL_DATABASE: wordpress_test
          WP_TESTS_DB_PASS: root

      - run: git diff --exit-code
